version: '3.9'

services:
  back:
    build: .
    volumes:
      - .:/fastapi_app
    command: [ "/src/docker/app.sh" ]
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://mongo_db
    env_file:
      - .env
    ports:
      - "8000:8000"

  mongo_db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  db:
    image: postgres:15.1
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data:


networks:
  default:
    name: fastapi_network
    external: true
